language: java
jdk:
  - oraclejdk8
before_script: cd ./BackEnd/a-world-of-plants
script: mvn test package
before_deploy:
  - cd target
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
deploy:
  skip_cleanup: true
  provider: script
  script: "../../../scripts/deploy.sh"
  on:
    branch: master
